## Numpy Tutorials

In [2]:
import numpy as np

In [173]:
lst = [1,2,3,4,5]
arry = np.array(lst)

In [175]:
print(arry)

[1 2 3 4 5]


In [75]:
arry.shape

(5,)

In [77]:
## Multinested array
my_lst1=[1,2,3,4,5]
my_lst2=[2,3,4,5,6]
my_lst3=[9,7,6,8,9]

arr=np.array([my_lst1,my_lst2,my_lst3])

In [79]:
print(arr)

[[1 2 3 4 5]
 [2 3 4 5 6]
 [9 7 6 8 9]]


In [81]:
arr1 = arr.reshape(5,3)

In [83]:
print(arr)

[[1 2 3 4 5]
 [2 3 4 5 6]
 [9 7 6 8 9]]


In [85]:
print(arr1)

[[1 2 3]
 [4 5 2]
 [3 4 5]
 [6 9 7]
 [6 8 9]]


In [87]:
arry[3]

4

In [89]:
arr[0:2, 0:3]

array([[1, 2, 3],
       [2, 3, 4]])

In [91]:
arr[1:4, 2:4]

array([[4, 5],
       [6, 8]])

In [93]:
arr[1:2, 1:4]

array([[3, 4, 5]])

In [95]:
arr2 = np.arange(0,9)

In [97]:
print(arr2)

[0 1 2 3 4 5 6 7 8]


In [133]:
arr3 = np.linspace(1,10,5)

In [135]:
arr3

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [177]:
arry

array([1, 2, 3, 4, 5])

In [183]:
arry[3: ] = 100
print(arry)

[  1   2   3 100 100]


In [203]:
aar = arry.copy()
aar2 = arry #changes original object values

In [193]:
aar[3: ] = 500
print(aar)

[  1   2   3 500 500]


In [201]:
print(arry)
aar2[3: ] = 200
print(aar2)
print(aar)

[  1   2   3 200 200]
[  1   2   3 200 200]
[  1   2   3 500 500]


In [205]:
arry[arry<2]

array([1])